### ISSUE TITLE
Can not open expand filters

### ISSUE THREAD

**Issue by hswhsy** [Sidekick-Poe/Sidekick#11]
Opening check price with ctrl+D doesn't make error.
But when I click "EXPAND FILTERS", an error occurs
I cannot close the error window with ESC or clicking "close window". alt + f4 only works
![sidekick_error](https://user-images.githubusercontent.com/45815623/132088064-22f6ee3b-9fc4-4638-ad05-f2d601d4f610.png)

**Comment by leMicin** [comment]
Hi, can you copy paste the item you are trying to expand filters for? I can't seem to reproduce your issue.

**Comment by ching756** [comment]
> Hi, can you copy paste the item you are trying to expand filters for? I can't seem to reproduce your issue.

I'm playing POE in Korean.
When I searched every rare or magic item via Ctrl+D, I meet same symptom.
Also I try to search aging, The SideKick is dead with below alert box.
![image](https://user-images.githubusercontent.com/90142140/132129071-e23b8abc-5c46-4219-b42a-40714f4fcf50.png)
It was happned since 2.2.0.

**Comment by hswhsy** [comment]
> Hi, can you copy paste the item you are trying to expand filters for? I can't seem to reproduce your issue.
all of items
I think it happens with Korean language.
There was no problem when I tried with English

**Comment by leMicin** [comment]
I will fix this very soon, sorry for the issue. :(
