### ISSUE TITLE
Implement new Installer and Updater using Velopack

### ISSUE THREAD

**Issue by pfeigl** [Sidekick-Poe/Sidekick#295]
With the 250mb every (very regular update) currently downloads, it might make sense to look at other options.
I successfully integrated `Squirrel.Windows` in the past, than it's predecessor `Clowd.Squirrel` and its current evolution namely https://github.com/velopack/velopack

These tools are the basis of the update process for tools like VSCode.

The huge benefit of it is the support for partial upgrades.

**Comment by domialex** [comment]
Haven't heard of Velopack, it looks interesting.
Right now this is low priority since we're trying to stabilize support for PoE2.
We could probably try to implement Velopack without changing our current ClickOnce deployment, since we also generate a portable version on the GitHub release.
The filesize mostly comes from the fact that we bundle the .NET runtime.

**Comment by leMicin** [comment]
ClickOnce also does partial updates, the updates go by much faster than the initial download. Though with many people encountering issues with ClickOnce, Velopack looks interesting indeed.

**Comment by pfeigl** [comment]
Oh, I wasn't actually aware, that ClickOnce is doing partial upgrades also. Just saw the progress bar running up over and over again.

> The filesize mostly comes from the fact that we bundle the .NET runtime.
You might want to look into possible building a trimmed self-contained build, as described here.
https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained
There are a few exceptions, where this is not going to work, but most of the time it just works or can be worked around.

**Comment by leMicin** [comment]
Microsoft does not recommend trimming for WPF apps.
